api_key = 'jXepnmVYibuE2E6MsQ2TRHdBD4dkxEAA0HDucwoMXxNbNY3hPVmPB329VkYkY3cz'
api_secret = 'na8CDIaNlIt7nlMcyndhVbb6cNbEtRRUVl9UfO0CCGOtlMYduuyimdwQySvYOpkH'
test_api_url = 'https://testnet.binance.vision/api'
api_url = 'https://api.binance.com/'
telebot_token = '2133047644:AAHutBsvIFOcIJv9rqDJWNxgKxIKDUHhlkg'
